name: Performance Test Manual WorkFlow using emulator

on:
  workflow_dispatch:
    inputs:
      info:
        description: 'For available devices and OS versions, visit: https://www.browserstack.com/list-of-browsers-and-platforms/app_automate'
        required: false
        default: 'Info: Visit the link above for device and OS options'
        type: string
      branch_name:
        description: 'Branch name to run tests on'
        required: true
        default: 'main'
        type: string
      device:
        description: 'Device to run tests on (e.g., Xiaomi Redmi Note 11)'
        required: false
        default: 'Xiaomi Redmi Note 11'
        type: string
      os_version:
        description: 'OS Version (e.g., 11.0)'
        required: false
        default: '11.0'
        type: string
      browserstack_app_url:
        description: 'Browserstack app URL'
        required: true
        type: string

jobs:
  run-performance-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      BROWSERSTACK_DEVICE: ${{ github.event.inputs.device || 'Xiaomi Redmi Note 11' }}
      BROWSERSTACK_OS_VERSION: ${{ github.event.inputs.os_version || '11.0' }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      MM_TEST_ACCOUNT_SRP: ${{ secrets.MM_TEST_ACCOUNT_SRP }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name || 'main' }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Download APK from GitHub Releases
        run: |
          # Download the latest APK from GitHub releases
          # You'll need to create a release with the APK file
          # Replace 'v1.0.0' with your actual release tag
          RELEASE_TAG="v1.0.0"
          APK_NAME="7.45.2.apk"
          
          # Download APK from releases
          curl -L -o $APK_NAME \
            "https://github.com/${{ github.repository }}/releases/download/$RELEASE_TAG/$APK_NAME"
          
          # Verify the file was downloaded
          ls -la $APK_NAME
          echo "APK downloaded successfully"
      
    #   - name: Install Fixture Server Dependencies
    #     run: |
    #       echo "Installing fixture server dependencies..."
    #       cd fixture-server
    #       yarn install --frozen-lockfile
      
    #   - name: Start Fixture Server
    #     run: |
    #       echo "Starting fixture server..."
    #       cd fixture-server
    #       yarn start & cd ..
    #       echo "Fixture server started in background"
    #       sleep 5
      
      - name: Install OpenJDK 17
        run: |
          echo "CPUSSSS" 
          lscpu
          echo "ARchetecture" 
          uname -m
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk
          java -version  # Verify Java installation
          
      - name: Install Android SDK dependencies
        run: |
          sudo apt-get install -y unzip curl
          
      - name: Setup Android SDK
        run: |
          # Create SDK directories
          export ANDROID_HOME=$HOME/Android/sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME

          # Download and extract command line tools
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip cmdline-tools.zip -d cmdline-tools

          # Move extracted tools to the correct directory
          mv cmdline-tools/cmdline-tools cmdline-tools/latest || true

          # Set environment variables
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Accept Android SDK Licenses
        run: |
          mkdir -p $ANDROID_HOME/licenses
          echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
          echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
          echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> $ANDROID_HOME/licenses/android-sdk-license
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Install Android Components
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "emulator"
          sdkmanager --install "system-images;android-34;google_apis;x86_64"
          yes | sdkmanager --licenses

      - name: Fix Missing INI File
        run: |
          mkdir -p $HOME/.android
          touch $HOME/.android/emu-update-last-check.ini
      
      - name: enable KVM for linux runners
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Create Emulator
        run: |
          # avdmanager list device
          echo "no" | avdmanager create avd \
          --name test_device \
          --package "system-images;android-34;google_apis;x86_64" \
          --device "pixel_6_pro"
          # sed -i '' 's/^hw.ramSize=.*/hw.ramSize=2048/' ~/.android/avd/test_device.avd/config.ini
          # # sed -i '' 's/^vm.heapSize=.*/vm.heapSize=1024/' ~/.android/avd/test_device.avd/config.ini
          # sed -i '' 's/^hw.cpu.cores=.*/hw.cpu.cores=4/' ~/.android/avd/test_device.avd/config.ini
          ls -la $HOME/.android/avd/

      - name: Start Emulator
        run: |
          echo "Starting Emulator..."
          # Using no-snapshot, no-window, no-metrics, and other optimizations
          nohup emulator -avd test_device -no-window -no-snapshot -no-audio -no-boot-anim -memory 2048 -no-metrics -grpc -grpc-use-jwt &
          adb start-server
          sleep 520
          adb shell am start -n com.google.android.apps.photos/.home.HomeActivity

      - name: Check Emulator status
        run: | 
          if [[ "$(adb shell getprop sys.boot_completed)" == "1" ]]; then
            echo "Emulator is fully booted!"
            adb shell input keyevent 82
            adb shell input touchscreen swipe 500 1000 500 500
          else
            echo "Emulator failed to boot properly within timeout"
            adb logcat -d
          fi
      
      - name: Take Screenshot
        run: |
          adb shell mkdir -p /data/local/tmp/screenshots
          adb shell chmod 777 /data/local/tmp/screenshots
          adb exec-out screencap -p > screenshot.png

      - name: Upload Screenshot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: emulator-screenshot
          path: screenshot.png
      
      - name: Run Android Performance Tests
        env:
          BROWSERSTACK_LOCAL: true
          BROWSERSTACK_LOCAL_IDENTIFIER: ${{ github.run_id }}
          APK_PATH: ./7.45.2.apk
        run: |
          echo "Running tests on branch: ${{ github.event.inputs.branch_name || 'main' }}"
          echo "Device: ${{ env.BROWSERSTACK_DEVICE }}"
          echo "OS Version: ${{ env.BROWSERSTACK_OS_VERSION }}"
          yarn test:wdio:mocha
      
    #   - name: Stop Fixture Server
    #     if: always()
    #     run: |
    #       echo "Stopping fixture server..."
    #       pkill -f "yarn start" || true
    #       echo "Fixture server stopped"