name: E2E Performance Tests

on:
  workflow_dispatch:
    inputs:
      info:
        description: 'For available devices and OS versions, visit: https://www.browserstack.com/list-of-browsers-and-platforms/app_automate'
        required: false
        default: 'Click the link above to see supported devices'
        type: string
      branch_name:
        description: 'Branch name to run tests on'
        required: true
        default: 'main'
        type: string
      device:
        required: false
        default: 'Xiaomi Redmi Note 11'
        type: string
      os_version:
        required: false
        default: '11.0'
        type: string
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  schedule:
    # Every 3 hours on main branch
    - cron: '0 */3 * * *'

jobs:
  run-performance-test:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_DEVICE: ${{ github.event.inputs.device || 'Xiaomi Redmi Note 11' }}
      BROWSERSTACK_OS_VERSION: ${{ github.event.inputs.os_version || '11.0' }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      MM_TEST_ACCOUNT_SRP: ${{ secrets.MM_TEST_ACCOUNT_SRP }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name || 'main' }}
      
      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          build-name: ${{ github.repository }}-${{ github.run_number }}
          project-name: ${{ github.repository }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Run Android Performance Tests
        run: |
          echo "Running tests on branch: ${{ github.event.inputs.branch_name || 'main' }}"
          echo "Device: ${{ env.BROWSERSTACK_DEVICE }}"
          echo "OS Version: ${{ env.BROWSERSTACK_OS_VERSION }}"
          yarn test:wdio:android:browserstack --performance